import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "../providers/QueryClientProvider";
import { StoresProvider } from "../contexts/StoresContext";
import { AuthProvider } from "../contexts/AuthContext";
import { CartProvider } from "../contexts/CartContext";
import NavBar from "../components/custom/navbar/NavBar";

const figtreeSans = Figtree({
  variable: "--font-figtree-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <StoresProvider>
          <AuthProvider>
            <CartProvider>
              <body className={`${figtreeSans.variable} font-sans antialiased`}>
                <NavBar />
                {children}
                <footer className="w-full bg-gray-900 text-gray-300 text-center py-8">
                  <p className="mb-4">
                    © {new Date().getFullYear()} Ecommerce. Todos os direitos
                    reservados.
                  </p>
                </footer>
              </body>
            </CartProvider>
          </AuthProvider>
        </StoresProvider>
      </ReactQueryProvider>
    </html>
  );
}
