import type { Metadata } from "next";
import { Figtree, Sora } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "../providers/QueryClientProvider";
import { StoresProvider } from "../contexts/StoresContext";
import { AuthProvider } from "../contexts/AuthContext";
import { CartProvider } from "../contexts/CartContext";
import NavBar from "../components/custom/navbar/NavBar";
import Footer from "../components/custom/footer/Footer";
import { Toaster } from "react-hot-toast";
import { OrdersProvider } from "../contexts/OrdersContext";

const figtreeSans = Figtree({
  variable: "--font-figtree-sans",
  subsets: ["latin"],
  display: "swap",
});
const soraSans = Sora({
  variable: "--font-sora-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <StoresProvider>
          <AuthProvider>
            <CartProvider>
              <OrdersProvider>
                <body
                  className={`${figtreeSans.variable} ${soraSans.variable} font-sans overflow-x-hidden antialiased`}
                >
                  <Toaster
                    position="top-center"
                    reverseOrder={false}
                    gutter={8}
                    toasterId="default"
                  />
                  <NavBar />
                  <main className="min-h-screen">{children}</main>
                  <Footer />
                </body>
              </OrdersProvider>
            </CartProvider>
          </AuthProvider>
        </StoresProvider>
      </ReactQueryProvider>
    </html>
  );
}
